In [45]:
import pandas as pd

# 创建一个具有多层索引的 DataFrame
data = {'A': [1, 3, 2], 'B': [4, 5, 6], 'C': [7, 8, 9]}
index = pd.MultiIndex.from_tuples([('x', 1), ('x', 2), ('y', 3)],
                                 names=('X', 'Y'))
df = pd.DataFrame(data, index=index)
display(df)
values = df.loc[('x'), :]
a = []
for i in df.index.levels[0]: # type: ignore ,levels在新版本pandas中被移除
    values = df.loc[i, 'A'].sum() # type: ignore
    a.append(values)
print(a)
df.sort_values(by='A', ascending=False, inplace=True)
display(df)
df.sort_values(by='B', ascending=False, inplace=True)
display(df)

A  B  C
X Y         
x 1  1  4  7
  2  3  5  8
y 3  2  6  9

[4, 2]


A  B  C
X Y         
x 2  3  5  8
y 3  2  6  9
x 1  1  4  7

A  B  C
X Y         
y 3  2  6  9
x 2  3  5  8
  1  1  4  7

In [3]:
import pandas as pd
import numpy as np

data = {'A': [1, np.nan, 3, np.nan, 5]}
df = pd.DataFrame(data)
display(df)

# 线性插值
df['A_linear_interpolated'] = df['A'].interpolate()
display(df)

# 二次插值
df['A_quadratic_interpolated'] = df['A'].interpolate(order=2)
display(df)

# 三次插值
df['A_cubic_interpolated'] = df['A'].interpolate(order=3)
display(df)

# 四次插值
df['A_quartic_interpolated'] = df['A'].interpolate(order=4)
display(df)


A
0  1.0
1  NaN
2  3.0
3  NaN
4  5.0

A  A_linear_interpolated
0  1.0                    1.0
1  NaN                    2.0
2  3.0                    3.0
3  NaN                    4.0
4  5.0                    5.0

A  A_linear_interpolated  A_quadratic_interpolated
0  1.0                    1.0                       1.0
1  NaN                    2.0                       2.0
2  3.0                    3.0                       3.0
3  NaN                    4.0                       4.0
4  5.0                    5.0                       5.0

A  A_linear_interpolated  A_quadratic_interpolated  A_cubic_interpolated
0  1.0                    1.0                       1.0                   1.0
1  NaN                    2.0                       2.0                   2.0
2  3.0                    3.0                       3.0                   3.0
3  NaN                    4.0                       4.0                   4.0
4  5.0                    5.0                       5.0                   5.0

A  A_linear_interpolated  A_quadratic_interpolated  A_cubic_interpolated  \
0  1.0                    1.0                       1.0                   1.0   
1  NaN                    2.0                       2.0                   2.0   
2  3.0                    3.0                       3.0                   3.0   
3  NaN                    4.0                       4.0                   4.0   
4  5.0                    5.0                       5.0                   5.0   

   A_quartic_interpolated  
0                     1.0  
1                     2.0  
2                     3.0  
3                     4.0  
4                     5.0

In [1]:
import numpy as np
a = np.arange(6)
display(a)
print(a)
b=a[0:1]
c=a[0]
display(b)
display(c)
display(id(a))
display(id(b))
display(id(c))
print(id(b))
print(id(c))
a[0]= 10
display(a)

array([0, 1, 2, 3, 4, 5])

[0 1 2 3 4 5]


array([0])

0

2642597537872

2642597534800

2642596583248

2642597534800
2642596583248


array([10,  1,  2,  3,  4,  5])